### ISSUE TITLE
Ignore Game Folder?

### ISSUE THREAD

**Issue by inc0der** [Guelstie/Guelstie-Plugins#4]
I wonder if we should ignore the game folder with git? Considering the game folder is specifically for testing our plugins while we work, I don't think it's really necessary to include the game in our repo and have it compare files from that folder. What are your thoughts on this?

**Comment by Troctzul** [comment]
I was honestly wondering why it was even in there. Figured you had a reason.

**Comment by inc0der** [comment]
It was for an easy start so everyone who contributes can just clone the repo and install dependencies. I'm starting to wonder if we just include the game folder but ignore it's contents and allow for the contributor to include their own game project to test with.

**Comment by Troctzul** [comment]
I suppose you anticipate that being a problem later on. If you think it is something you should take care of now, I don't mind.

**Comment by inc0der** [comment]
Okay, once I get to work on the repo again, I'll ignore the contents of the game folder, I think it will keep things cleaner and should avoid any issues with pull requests in the future.
